@tool
## A script that automatically creates pal definitions in order using it's internal list of pals.
## This is a destructive operation, so be sure to back up existing definitions 
## before running it in order to prevent loss of data.
extends EditorScript

const OUTPUT_DIR: String = "res://pals/definitions/"
const PORTRAIT_DIR: String = "res://pals/portraits/"

func _run() -> void:
	var previous_pal: String = ""
	var species_variant: int = 0
	var pal_index: int = 0
	for pal in pals:
		# if the pal name starts with the name of the previous pal, it is a sub-pecies and shouldn't increment
		if (not pal.begins_with(previous_pal)) or (pal.length() > previous_pal.length() and pal[previous_pal.length()] != " "):
			pal_index += 1
			previous_pal = pal
			species_variant = 0
		else:
			species_variant += 1
		
		var paldex_entry_string: String = "%03d%s: %s" % [
			pal_index, 
			char(65 + species_variant),
			pal
		]
		
		var pal_resource := PalResource.new()
		pal_resource.resource_path = OUTPUT_DIR.path_join(paldex_entry_string.replace(" ", "_").remove_chars(":").to_lower() + ".tres")
		pal_resource.resource_name = pal
		pal_resource.translation_key = "pal_" + pal.to_snake_case()
		pal_resource.paldex_entry = pal_index
		pal_resource.species_variant = species_variant
		
		var portrait_file := PORTRAIT_DIR.path_join(pal.replace(" ", "_") + ".webp")
		if FileAccess.file_exists(portrait_file):
			pal_resource.visual = load(portrait_file)
		else:
			push_warning("'%s' was not found" % portrait_file)
		
		ResourceSaver.save(pal_resource)


const pals: Array[String] = [
	"Lamball",
	"Cattiva",
	"Chikipi",
	"Lifmunk",
	"Fuack",
	"Fuack Ignis",
	"Vixy",
	"Celaray",
	"Celaray Lux",
	"Cremis",
	"Croajiro",
	"Croajiro Noct",
	"Herbil",
	"Teafant",
	"Gumoss",
	"Pupperai",
	"Clovee",
	"Jolthog",
	"Jolthog Cryst",
	"Depresso",
	"Pengullet",
	"Pengullet Lux",
	"Penking",
	"Penking Lux",
	"Hoocrates",
	"Melpaca",
	"Kingpaca",
	"Kingpaca Cryst",
	"Daedream",
	"Tanzee",
	"Nox",
	"Flambelle",
	"Rooby",
	"Mau",
	"Mau Cryst",
	"Rushoar",
	"Foxparks",
	"Foxparks Cryst",
	"Killamari",
	"Killamari Primo",
	"Fuddler",
	"Eikthyrdeer",
	"Eikthyrdeer Terra",
	"Direhowl",
	"Caprity",
	"Caprity Noct",
	"Swee",
	"Sweepa",
	"Turtacle",
	"Turtacle Terra",
	"Hangyu",
	"Hangyu Cryst",
	"Woolipop",
	"Woolipop Terra",
	"Mozzarina",
	"Azurobe",
	"Azurobe Cryst",
	"Sparkit",
	"Kelpsea",
	"Kelpsea Ignis",
	"Ribbuny",
	"Ribbuny Botan",
	"Jelliette",
	"Jellroy",
	"Amione",
	"Gloopie",
	"Gloopie Primo",
	"Galeclaw",
	"Wispaw",
	"Nitewing",
	"Tombat",
	"Tocotoco",
	"Univolt",
	"Univolt Cryst",
	"Gobfin",
	"Gobfin Ignis",
	"Loupmoon",
	"Loupmoon Cryst",
	"Cawgnito",
	"Arsox",
	"Muffly",
	"Bristla",
	"Cinnamoth",
	"Puffolt",
	"Elphidran",
	"Elphidran Aqua",
	"Vanwyrm",
	"Vanwyrm Cryst",
	"Felbat",
	"Vaelet",
	"Beegarde",
	"Elizabee",
	"Lovander",
	"Grintale",
	"Tarantriss",
	"Polapup",
	"Polapup Terra",
	"Leezpunk",
	"Leezpunk Ignis",
	"Gorirat",
	"Gorirat Terra",
	"Surfent",
	"Surfent Terra",
	"Robinquill",
	"Robinquill Terra",
	"Flopie",
	"Wixen",
	"Wixen Noct",
	"Katress",
	"Katress Ignis",
	"Helzephyr",
	"Helzephyr Lux",
	"Elgrove",
	"Elgrove Cryst",
	"Lunaris",
	"Fenglope",
	"Fenglope Lux",
	"Dinossom",
	"Dinossom Lux",
	"Bushi",
	"Bushi Noct",
	"Munchill",
	"Mammorest",
	"Mammorest Cryst",
	"Finsider",
	"Finsider Ignis",
	"Petallia",
	"Petallia Ignis",
	"Leafan",
	"Incineram",
	"Incineram Noct",
	"Dazzi",
	"Dazzi Noct",
	"Pyrin",
	"Pyrin Noct",
	"Relaxaurus",
	"Relaxaurus Lux",
	"Foxcicle",
	"Beakon",
	"Beakon Cryst",
	"Ghangler",
	"Ghangler Ignis",
	"Rayhound",
	"Rayhound Cryst",
	"Menasting",
	"Menasting Terra",
	"Needoll",
	"Needoll Noct",
	"Reindrix",
	"Mossanda",
	"Mossanda Lux",
	"Chillet",
	"Chillet Ignis",
	"Ragnahawk",
	"Moldron",
	"Moldron Cryst",
	"Palumba",
	"Digtoise",
	"Broncherry",
	"Broncherry Aqua",
	"Dumud",
	"Dumud Gild",
	"Braloha",
	"Kitsun",
	"Kitsun Noct",
	"Blazehowl",
	"Blazehowl Noct",
	"Warsect",
	"Warsect Terra",
	"Frostplume",
	"Majex",
	"Sibelyx",
	"Sibelyx Primo",
	"Maraith",
	"Shroomer",
	"Shroomer Noct",
	"Icelyn",
	"Gildra",
	"Jormuntide",
	"Jormuntide Ignis",
	"Suzaku",
	"Suzaku Aqua",
	"Dazemu",
	"Quivern",
	"Quivern Botan",
	"Lullu",
	"Kikit",
	"Yakumo",
	"Skutlass",
	"Skutlass Ignis",
	"Reptyro",
	"Reptyro Cryst",
	"Starryon",
	"Starryon Primo",
	"Pierdon",
	"Pierdon Cryst",
	"Cryolinx",
	"Cryolinx Terra",
	"Snugloo",
	"Wumpo",
	"Wumpo Botan",
	"Sootseer",
	"Carnibora",
	"Blazamut",
	"Blazamut Ryu",
	"Dualith",
	"Dualith Noct",
	"Anubis",
	"Sekhmet",
	"Prixter",
	"Prixter Lux",
	"Tetroise",
	"Tetroise Primo",
	"Nyafia",
	"Mimog",
	"Xenovader",
	"Xenogard",
	"Prunelia",
	"Nitemary",
	"Nitemary Botan",
	"Smokie",
	"Smokie Cryst",
	"Omascul",
	"Whalaska",
	"Whalaska Ignis",
	"Verdash",
	"Splatterina",
	"Gildane",
	"Dogen",
	"Bulldosu",
	"Celesdir",
	"Celesdir Noct",
	"Astegon",
	"Knocklem",
	"Knocklem Ignis",
	"Silvegis",
	"Azurmane",
	"Valentail",
	"Snock",
	"Snock Terra",
	"Souffline",
	"Lapiron",
	"Hoodle",
	"Slowatt",
	"Bakemi",
	"Solmora",
	"Solmora Lux",
	"Lapure",
	"Eidrolon",
	"Eidrolon Ignis",
	"Dynamoff",
	"Tropicaw",
	"Flaracle",
	"Ophydia",
	"Dupin",
	"Roujay",
	"Venusa",
	"Mycora",
	"Loomen",
	"Wistella",
	"Solenne",
	"Renjishi",
	"Aegidron",
	"Grizzbolt",
	"Lyleen",
	"Lyleen Noct",
	"Orserk",
	"Faleris",
	"Faleris Aqua",
	"Shadowbeak",
	"Selyne",
	"Bastigor",
	"Shaolong",
	"Silvance",
	"Dandilord",
	"Bellanoir",
	"Bellanoir Libero",
	"Xenolord",
	"Hartalis",
	"Paladius",
	"Necromus",
	"Frostallion",
	"Frostallion Noct",
	"Neptilius",
	"Jetragon",
	"Panthalus",
	"Astralym"
]
